
["Mutant Stats"]
	damage = 1.0
	health = 1.0
	speed = 1.0
	attack_knockback = 1.0
	knockback_resistance = 1.0
	follow_range = 1.0

["Mutant Spawning"]
	#Spawn chance. Default: 1
	spawnChance = 1.0
	#The second modifier for mob spawning
	spawnChanceModifier = 1.0
	#The number spawnChance is divided by to have the final number as a chance for spawning
	spawnScaling = 10.0

["Mob Abilities"]
	#Mobs in tag mutant_entities:extralives maximum lives. Default: 5
	maxlives = 5.0
	#The chance of a mutant zombie doing the grab and leap attack. Default 0.2, meaning 20%
	leap_chance = 0.2
	#Chance for mutant zombie slam attack. Default: 0.25
	slam_chance = 0.25
	#Mutant Zombie roar attack to summon other zombies
	roar_chance = 0.1

["Item Stats"]
	#Attack damage of golden hammer
	goldenhammerdmg = 10.0
	#Attack speed of golden hammer
	goldenhammerspd = -2.8
	#Attack damage of wither sword
	withersworddmg = 10.0
	#Attack speed of wither sword
	witherswordspd = -2.6

